name: Build and Test

on:
  push:
    branches: 
      - 'feature/**'
      - 'master'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Or another preferred OS

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Replace with your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test /p:CollectCoverage=true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: KarelDolansky/Weather_App
          file: home/runner/work/Weather_App/Weather_App/Weather_App.Tests/coverage.json
