name: Build and Test

on:
  push:
    branches: 
      - 'feature/**'
      - 'main'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Or another preferred OS

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Replace with your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal \
             --test-assembly-path **/Weather\ App.Tests/bin/Debug/netcoreapp3.1/Weather\ App.Tests.dll  # Adjust path and .NET version if needed

